DROP SEQUENCE SEQ_BOOK;
DROP TABLE BOOK CASCADE CONSTRAINTS;

CREATE SEQUENCE SEQ_BOOK NOCACHE NOCYCLE;
CREATE TABLE BOOK (
    ID NUMBER DEFAULT SEQ_BOOK.NEXTVAL PRIMARY KEY,
    NAME VARCHAR2(255),
    DESCRIPTION VARCHAR2(2000),
    DEL_YN CHAR(1) DEFAULT 'N' CHECK (DEL_YN IN ('Y', 'N'))
);

INSERT INTO BOOK (ID, NAME, DESCRIPTION) VALUES (SEQ_BOOK.NEXTVAL, 'Book 1', 'Description 1');
INSERT INTO BOOK (ID, NAME, DESCRIPTION) VALUES (SEQ_BOOK.NEXTVAL, 'Book 2', 'Description 2');
INSERT INTO BOOK (ID, NAME, DESCRIPTION) VALUES (SEQ_BOOK.NEXTVAL, 'Book 3', 'Description 3');
INSERT INTO BOOK (ID, NAME, DESCRIPTION) VALUES (SEQ_BOOK.NEXTVAL, 'Book 4', 'Description 4');
INSERT INTO BOOK (ID, NAME, DESCRIPTION) VALUES (SEQ_BOOK.NEXTVAL, 'Book 5', 'Description 5');

select * from book;